MAINMENU = "0"

START_GREETINGS = "1"
START_STUDENT = "2"
START_TEACHER = "3"
START_ABITUR = "4"
START_THANKS = "5"

CLEAR_СONFIRMATION = "6"
CLEAR_BYE = "7"
CLEAR_CANCEL = "8"

TIMETABLE_TODAY = "9"
TIMETABLE_NOCONECTION = "10"
TIMETABLE_WRONGGROUP = "11"
TIMETABLE_NOTABLE = "12"

ERROR_WRONG_INPUT = "13"
ERROR_WRONG_CHOICE = "14"
ERROR_SOMTING_WRONG = "15"

U_HAVE_QUEST = "16"
ASK_QUESTION = "17"
QUEST_WRITED = "18"
NO_QUESTION = "19"
ANSWER_SENDED = "20"
ANSWER_FOR_YOU = "21"
SETTINGS_MENU = "22"
DEV = "23"
ABOUT = "24"

CHANGE_TYPE = "25"
CHANGE_GROUPE = "26"
CHANGE_NAME = "27"

AUTO_ON = "28"
AUTO_OFF = "29"

UI_RELOAD = "30"

QUEST_FOR_YOU = "31"
ENTER_ANSWER = "32"

QUEST_DELETED = "33"
QUEST_NUMBER = "34"

BUILDING_G = "35"
BUILDING_D = "36"
BUILDING_I = "37"
BUILDING_A = "38"
BUILDING_E = "39"
BUILDING_K = "40"
BUILDING_V = "41"
BUILDING_B = "42"

BUILDING_INFO_G = "43"
BUILDING_INFO_D = "44"
BUILDING_INFO_I = "45"
BUILDING_INFO_A = "46"
BUILDING_INFO_E = "47"
BUILDING_INFO_K = "48"
BUILDING_INFO_V = "49"
BUILDING_INFO_B = "50"

CHOOSE_BUILD = "51"

SUNDAY = "52"

VK_SHOW = "53"

EXPENDED_SEARCH = '54'
EXPENDED_GP = '55'
EXPENDED_DAY = '56'

RETAKE = '57'
DOORS = '58'