MAINMENU = '0'

START_GREETINGS = '1'
START_STUDENT = '2'
START_TEACHER = '3'
START_ABITUR = '4'
START_THANKS = '5'
    
CLEAR_СONFIRMATION = '6'
CLEAR_BYE = '7'
CLEAR_CANCEL = '8'

TIMETABLE_TODAY = '9'
TIMETABLE_NOCONECTION = '10'
TIMETABLE_WRONGGROUP = '11'
TIMETABLE_NOTABLE = '12'

ERROR_WRONG_INPUT = '13'
ERROR_WRONG_CHOICE = '14'
ERROR_SOMTING_WRONG = '15'

U_HAVE_QUEST = '16'
ASK_QUESTION = '17'
QUEST_WRITED = '18'
NO_QUESTION = '19'
ANSWER_SENDED = '20'
ANSWER_FOR_YOU = '21'
SETTINGS_MENU = '22'
DEV = '23'
ABOUT = '24'

CHANGE_TYPE = '25'
CHANGE_GROUPE = '26'
CHANGE_NAME = '27'

AUTO_ON = '28'
AUTO_OFF = '29'

UI_RELOAD = '30'

QUEST_FOR_YOU = '31'
ENTER_ANSWER = '32'