from . import start_handlers
from . import back_handler
from . import clear_handlers
from . import staff_handler
from . import timetable_handlers
from . import questions_handler
from . import vk_handler
from . import settings_handler
from . import buildings_handler
from . import retake_handler
from . import door_handler
from . import direction_handler
from . import end_handler